from django.db import models
from django.conf import settings
import random 


User = settings.AUTH_USER_MODEL

# Foreign key - obcy klucz. Informacja że istneije relacja z inną 
# tabelą bazy danych. Podając obcy klucz jako user i ustawiając wartość  np na 1 wiemy, że chodzi nam o pierwszeo użytkownika w tabeli users bazy danych.
class Tweet(models.Model):
  #  MAPS TO SQL DATA
  # Automatically generated by django is id:
  #id = models.AutoFiels(primary_key=True)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  content = models.TextField()
  image = models.FileField(upload_to='images/', blank=True, null=True)


  def __str__(self):
    return self.content

  # Reordering tweets to see the oldest at the bottom
  class Meta:
    ordering = ['-id']

  def serialize(self):
    return{
      "id": self.id,
      "content": self.content,
      "likes": random.randint(0,200)
    }
  